#!/bin/ksh
 
#-------------------------------------------------------
# Script to run the 'c' unit test on WCOSS-Cray
# compute nodes.
#
# Invoke this script as follows:
# "cat run.wcoss-cray.lsf | bsub"
#
# Output is put in "unit_test.log"
#-------------------------------------------------------

#BSUB -oo unit_test.log
#BSUB -eo unit_test.log
#BSUB -q debug
#BSUB -J ip2_c_unit_test
#BSUB -P GFS-T2O
#BSUB -M 500
#BSUB -extsched 'CRAYLINUX[]'
#BSUB -W 0:01

set -x

export NODES=1
export OMP_NUM_THREADS=1

export APRUN="aprun -j 1 -n 1 -d ${OMP_NUM_THREADS} "

run_unit_test.ksh

exit 0
