#!/bin/sh
 
#----------------------------------------------------------
# Script to run the copygb2 regression test on WCOSS-Cray.
#
# Invoke this script as follows:
# "cat run.wcoss.cray.lsf | bsub"
#----------------------------------------------------------

#BSUB -oo copygb2.log
#BSUB -eo copygb2.log
#BSUB -q dev_shared
#BSUB -J copygb2
#BSUB -R rusage[mem=400]
#BSUB -P GFS-T2O
#BSUB -W 0:15

set -x

module list

export OMP_NUM_THREADS=1

export REG_DIR=${LS_SUBCWD}/../..

export WORK_DIR="/gpfs/hps/ptmp/$LOGNAME/regression"

$REG_DIR/copygb2/scripts/copygb2.ksh

exit 0
