name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: checkout-sp
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sp
        path: sp
        ref: develop

    - name: build-sp
      run: |
        cd sp
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/sp
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: ip2
        submodules: true

    - name: build
      run: |
        cd ip2
        mkdir build 
        cd build
        cmake .. -DOPENMP=ON -DCMAKE_PREFIX_PATH="~/"
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/ip2/build
        ctest --verbose
